//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Котельня.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursavayaEntities : DbContext
    {
        private static KursavayaEntities _context;

        public KursavayaEntities()
            : base("name=KursavayaEntities")
        {
        }
        public static KursavayaEntities GetContext()
        {
            if (_context == null)
                _context = new KursavayaEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_composition> Order_composition { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Treaty> Treaty { get; set; }
        public virtual DbSet<Treaty_prepayment> Treaty_prepayment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Work> Work { get; set; }
        public virtual DbSet<WorkType> WorkType { get; set; }
    }
}
