//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Котельня.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_composition
    {
        public int id { get; set; }
        public int Order_id { get; set; }
        public int WorkType_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
