//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Котельня.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treaty
    {
        public int id { get; set; }
        public int User_id { get; set; }
        public System.DateTime First_Date { get; set; }
        public System.DateTime Last_Date { get; set; }
        public int Prepayment_id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Treaty_prepayment Treaty_prepayment { get; set; }
    }
}
